name = "qianyan-register"
main = "src/index.ts"
compatibility_date = "2024-07-30"

# 替换弃用的 node_compat 参数
compatibility_flags = [ "nodejs_compat" ]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "qianyan-register"
database_id = "400a78d2-2104-42e6-ad44-8f0397f723cd"

kv_namespaces = [
  { binding = "qianyan-register_limite", id = "95eb4f7afa0b4f1384adb18d1c93449b" }
]