name = "qianyan-register"
main = "src/signup.ts"
compatibility_date = "2024-07-30"

# 替换弃用的 node_compat 参数
compatibility_flags = [ "nodejs_compat" ]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "qianyan-register"
database_id = "400a78d2-2104-42e6-ad44-8f0397f723cd"